# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/wazo-ui/conf.d/

# Change the log level to debug level.
debug: false

# Log file.
log_filename: /var/log/wazo-ui.log

# PID file.
pid_filename: /var/run/wazo-ui/wazo-ui.pid

https:
  listen: 0.0.0.0
  port: 9296
  certificate: /usr/share/xivo-certs/server.crt
  private_key: /usr/share/xivo-certs/server.key

auth:
  host: localhost
  port: 9497
  verify_certificate: /usr/share/xivo-certs/server.crt

confd:
  host: localhost
  port: 9486
  verify_certificate: /usr/share/xivo-certs/server.crt

user: wazo-ui

enabled_plugins:
  - authentication: true
  - index: true
  - application: true
  - agent: true
  - asterisk_cli: true
  - call_filter: true
  - call_permission: true
  - call_pickup: true
  - cdr: true
  - conference: true
  - context: true
  - device: true
  - dird_profile: true
  - dird_source: true
  - dhcp: true
  - extension: true
  - external_auth: true
  - funckey: true
  - general_settings: true
  - group: true
  - ha: true
  - hep: true
  - identity: true
  - incall: true
  - ivr: true
  - line: true
  - moh: true
  - outcall: true
  - paging: true
  - parking_lot: true
  - plugin: true
  - provisioning: true
  - queue: true
  - rtp: true
  - schedule: true
  - skill: true
  - skillrule: true
  - sound: true
  - switchboard: true
  - trunk: true
  - user: true
  - voicemail: true
  - webhook: true
